name: PR preview

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '**'

jobs:
  check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
    env:
      DEPTH: 18
      AMOUNT: 100
      REACT_APP_BEE_HOST: http://165.227.165.55:1633
      REACT_APP_BEE_DEBUG_HOST: http://165.227.165.55:1635

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      ## Try getting the node modules from cache, if failed npm ci
      - uses: actions/cache@v2
        id: cache-npm
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ matrix.node }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-${{ matrix.node-version }}-${{ env.cache-name }}-
            ${{ runner.OS }}-node-${{ matrix.node-version }}-

      - name: Install npm deps
        if: steps.cache-npm.outputs.cache-hit != 'true'
        run: npm ci

      - name: Build
        run: npm run build

      - name: Install swarm-cli
        run: npm i @ethersphere/swarm-cli -g

      - name: Upload to Swarm
        run: |
          STAMP=$(swarm-cli stamp buy --depth ${{ env.DEPTH }} --amount ${{ env.AMOUNT }}  --bee-debug-api-url ${{ env.REACT_APP_BEE_DEBUG_HOST }} --quiet)
          sleep 30
          HASH=$(swarm-cli upload ./build --bee-api-url ${{ env.REACT_APP_BEE_HOST }} --quiet --stamp $STAMP)
          echo "PREVIEW_URL=${{ env.REACT_APP_BEE_HOST }}/bzz/$HASH" >> $GITHUB_ENV

      - name: Find preview comment
        uses: peter-evans/find-comment@v1
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: PR preview in Swarm

      - name: Create or update preview comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            PR preview in Swarm
            ${{ env.PREVIEW_URL }}
            git hash: ${{ github.event.payload.head }}
          edit-mode: replace
